---
# Areas
- name: area/docs
  color: "0e8a16"
# Renovate Types
- name: renovate/container
  color: "027fa0"
- name: renovate/github-action
  color: "027fa0"
- name: renovate/github-release
  color: "027fa0"
- name: renovate/helm
  color: "027fa0"
- name: renovate/dotnet
  color: "5319E7"
- name: renovate/nuget
  color: "0052CC"
- name: renovate/python
  color: "0e8a16"
# Semantic Types
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
