services:
  rabbitmq:
    container_name: rabbitmq
    image: docker.io/masstransit/rabbitmq:4.0.2
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - com
  localstack:
    container_name: localstack
    image: docker.io/localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "$XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock"
    networks:
      - com
  postgres:
    container_name: postgres
    image: docker.io/library/postgres:16.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "dotbot"
      POSTGRES_PASSWORD: "yourWeak(!)Password"
      POSTGRES_DB: "dotbot"
    networks:
      - com

  ngrok:
    container_name: ngrok
    image: docker.io/ngrok/ngrok:alpine
    env_file: .env
    command: 'http 127.0.0.1:5292'
    network_mode: "host"
    
  # ********************
  # Telemetry Components
  # ********************
  # Jaeger
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.53
    container_name: jaeger
    command:
      - "--memory.max-traces=5000"
      - "--query.base-path=/jaeger/ui"
      - "--prometheus.server-url=http://prometheus:9090"
      - "--prometheus.query.normalize-calls=true"
      - "--prometheus.query.normalize-duration=true"
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "16686:16686"         # Jaeger UI
      - "4317"
    environment:
      - METRICS_STORAGE_TYPE=prometheus
    networks:
      - com
  # Grafana
  grafana:
    image: docker.io/grafana/grafana:10.3.1
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=grafana-opensearch-datasource"
    volumes:
      - ../grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../grafana/provisioning/:/etc/grafana/provisioning/:U
    ports:
      - "3000:3000"

  # OpenTelemetry Collector
  otelcol:
    image: docker.io/otel/opentelemetry-collector-contrib:0.93.0
    container_name: otel-col
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ../otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
    networks:
      - com

  # Prometheus
  prometheus:
    image: quay.io/prometheus/prometheus:v2.49.1
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
    volumes:
      - ../prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - com
  loki:
    container_name: loki
    image: docker.io/grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - com
networks:
  com: {}