version: '3.8'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:

  rabbitmq:
    container_name: rabbitmq
    image: docker.io/rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  localstack:
    container_name: localstack
    image: docker.io/localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "$XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock"
#  mongo:
#    container_name: mongo
#    image: docker.io/library/mongo:7.0
#    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
#    ports:
#      - 27017:27017
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    healthcheck:
#      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
#      interval: 5s
#      timeout: 30s
#      start_period: 0s
#      retries: 30

  ngrok:
    container_name: ngrok
    image: docker.io/ngrok/ngrok:alpine
    environment:
      - NGROK_AUTHTOKEN
    command: 'http 127.0.0.1:5292'
    network_mode: "host"
    
  # ********************
  # Telemetry Components
  # ********************
  # Jaeger
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.53
    container_name: jaeger
    command:
      - "--memory.max-traces=5000"
      - "--query.base-path=/jaeger/ui"
      - "--prometheus.server-url=http://prometheus:9090"
      - "--prometheus.query.normalize-calls=true"
      - "--prometheus.query.normalize-duration=true"
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - 16686:16686         # Jaeger UI
      - "4317"
    environment:
      - METRICS_STORAGE_TYPE=prometheus
    logging: *logging

  # Grafana
  grafana:
    image: docker.io/grafana/grafana:10.3.1
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=grafana-opensearch-datasource"
    volumes:
      - ../grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../grafana/provisioning/:/etc/grafana/provisioning/:U
    ports:
      - 3000:3000
    logging: *logging

  # OpenTelemetry Collector
  otelcol:
    image: docker.io/otel/opentelemetry-collector-contrib:0.93.0
    container_name: otel-col
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ../otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
    logging: *logging

  # Prometheus
  prometheus:
    image: quay.io/prometheus/prometheus:v2.49.1
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
    volumes:
      - ../prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "9090:9090"
    logging: *logging

  loki:
    container_name: loki
    image: docker.io/grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
volumes:
  mongo_data:
  mongo_config: