apiVersion: v2
description: A Helm chart for Kubernetes
type: application
maintainers:
  - name: sillock1
    url: https://github.com/sillock1
name: dotbot
version: 0.8.3
appVersion: "1.0.2"
home: https://github.com/opentoucan/dotbot
