nameOverride: ""
fullnameOverride: ""
global:
  env:
    ASPNETCORE_ENVIRONMENT: 'Production'
gateway:
  replicaCount: 1
  image:
    repository: "ghcr.io/opentoucan"
    tag: "2.0.0"
    imagePullPolicy: IfNotPresent
    name: "dotbot.gateway"
    digest: "sha256:a756fb0969074645ec22091d9bb1b7a2e004e07fbcab59568b95c2ec2eb140f4"
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsUser: 2048
    runAsGroup: 2048
    fsGroup: 2048
    supplementalGroups: [2048]
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 2048
    allowPrivilegeEscalation: false
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumes: []
  volumeMounts: []

migrator:
  image:
    repository: "ghcr.io/opentoucan"
    tag: "2.0.0"
    imagePullPolicy: IfNotPresent
    name: "dotbot.migration"
    digest: "sha256:0ac02d48b5051832f2f3a9fb02e6b6138276428dfa9e882d165d52a675c2138a"
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsUser: 2048
    runAsGroup: 2048
    fsGroup: 2048
    supplementalGroups: [2048]
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 2048
    allowPrivilegeEscalation: false
  volumes:
    - name: cache-volume
      emptyDir:
        sizeLimit: 500Mi
  volumeMounts:
    - mountPath: /cache
      name: cache-volume
  env:
    - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
      value: /cache

# environment variables for configMap
env: {}
#  RabbitMQ__Endpoint: 'rabbitmq'
#  RabbitMQ__port: '5672'
#  S3__ServiceUrl: 'minio:9000'
#  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://opentelemetry-operator.default.svc.cluster.local:8080' 
configMapAnnotations: {}

# Secrets
existingAppSecret: ''
existingMigratorSecret: ''
# discord:
#   publicKey: ''
#   botToken: ''
#   webhooks:
#     xkcd: ''
# appUserDBConnectionString: ''
# migratorUserDBConnectionString: ''
# rabbitMQCredentials:
#   user: 'test'
#   password: 'test'
# objectStorageCredentials:
#   accessKeyId: 'dev'
#   secretAccessKey: 'dev'

service:
  name: http
  type: LoadBalancer
  port: 80
  targetPort: 8080
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - dotbot.local
  tls: []

jobs: []