nameOverride: ""
fullnameOverride: ""
global:
  env:
    ASPNETCORE_ENVIRONMENT: 'Production'
gateway:
  replicaCount: 1
  image:
    repository: "ghcr.io/opentoucan"
    tag: "1.0.7"
    imagePullPolicy: IfNotPresent
    name: "dotbot.gateway"
    digest: "sha256:c03514f6f9b20a26b8d46cdbe7923966dce3cdc9c14b559d63e79e82aa15f7ec"
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsUser: 1024
    runAsGroup: 1024
    fsGroup: 1024
    supplementalGroups: [1024]
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1024
    allowPrivilegeEscalation: false
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumes: []
  volumeMounts: []

migrator:
  image:
    repository: "ghcr.io/opentoucan"
    tag: "1.0.7"
    imagePullPolicy: IfNotPresent
    name: "dotbot.migration"
    digest: "sha256:b1b061fda9a8502e22fce4fcb491261b20589c0501764631e2841f46d33d565f"
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsUser: 1024
    runAsGroup: 1024
    fsGroup: 1024
    supplementalGroups: [1024]
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1024
    allowPrivilegeEscalation: false
  volumes:
    - name: cache-volume
      emptyDir:
        sizeLimit: 500Mi
  volumeMounts:
    - mountPath: /cache
      name: cache-volume
  env:
    - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
      value: /cache

# environment variables for configMap
env: {}
#  RabbitMQ__Endpoint: 'rabbitmq'
#  RabbitMQ__port: '5672'
#  S3__ServiceUrl: 'minio:9000'
#  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://opentelemetry-operator.default.svc.cluster.local:8080' 
configMapAnnotations: {}

# Secrets
existingAppSecret: ''
existingMigratorSecret: ''
# discord:
#   publicKey: ''
#   botToken: ''
#   webhooks:
#     xkcd: ''
# appUserDBConnectionString: ''
# migratorUserDBConnectionString: ''
# rabbitMQCredentials:
#   user: 'test'
#   password: 'test'
# objectStorageCredentials:
#   accessKeyId: 'dev'
#   secretAccessKey: 'dev'

service:
  name: http
  type: LoadBalancer
  port: 80
  targetPort: 8080
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - dotbot.local
  tls: []

jobs:
  - name: xkcd-job
    securityContext:
      runAsUser: 1024
      runAsGroup: 1024
      fsGroup: 1024
    image:
      repository: "ghcr.io/opentoucan"
      tag: "1.0.7"
      imagePullPolicy: Always
      name: "xkcd.job"
      digest: "sha256:3ffc8cd2695ed04371433354a9f108e613d2b76e52710d5655878a367af322c0"
    schedule: "0 * * * 1,3,5"
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
    ttlSecondsAfterFinished: 2400
