nameOverride: ""
fullnameOverride: ""
gateway:
  replicaCount: 1
  image:
    repository: "ghcr.io/sillock-inc/bot.gateway"
    tag: "0.3.11"
    digest: "sha256:62bd80d8e594e226c610c5451a5dda97ac0af4a454d403af3731665e97f5fd9d"
    pullPolicy: IfNotPresent
  secretName: dotbot-secret
  podAnnotations: { }
  podLabels: { }
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 2000
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumes: [ ]
  volumeMounts: [ ]

service:
  name: http
  type: LoadBalancer
  port: 80
  targetPort: 80
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - dotbot.local
  tls: []

jobs:
  - name: xkcd-job
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: "ghcr.io/sillock-inc/xkcd.job"
      tag: "0.3.11"
      digest: "sha256:5f892f30dc97e9f2030162e28ef73d2f3033a03a4099aea921af565db2f33c41"
      imagePullPolicy: Always
    env: []
    secretName: dotbot-secret
    schedule: "0 * * * *"
    serviceAccount:
      name: "xkcd-job"
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
