nameOverride: ""
fullnameOverride: ""
gateway:
  replicaCount: 1
  image:
    repository: "ghcr.io/sillock-inc/bot.gateway"
    tag: "0.3.13"
    digest: "sha256:23aeb251d39ac38a3f0d5b2fd6dcd49f60daae46e4a502a9b01d7144c6ac1348"
    pullPolicy: IfNotPresent
  secretName: dotbot-secret
  podAnnotations: { }
  podLabels: { }
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 2000
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumes: [ ]
  volumeMounts: [ ]

service:
  name: http
  type: LoadBalancer
  port: 80
  targetPort: 80
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - dotbot.local
  tls: []

jobs:
  - name: xkcd-job
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: "ghcr.io/sillock-inc/xkcd.job"
      tag: "0.3.13"
      digest: "sha256:d7148df8f58a1b0414d1423453d573642f20eb45f8be46f9a6785753180b8b35"
      imagePullPolicy: Always
    env: []
    secretName: dotbot-secret
    schedule: "0 * * * *"
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
