nameOverride: ""
fullnameOverride: ""
gateway:
  replicaCount: 1
  image:
    repository: "ghcr.io/sillock-inc/bot.gateway"
    tag: "0.3.15"
    digest: "sha256:15f19e01d99f7f1d5c24552000737af027b4f5c78de292cc8037dc88df15adee"
    pullPolicy: IfNotPresent
  secretName: dotbot-secret
  podAnnotations: { }
  podLabels: { }
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 2000
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumes: [ ]
  volumeMounts: [ ]

service:
  name: http
  type: LoadBalancer
  port: 80
  targetPort: 80
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - dotbot.local
  tls: []

jobs:
  - name: xkcd-job
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: "ghcr.io/sillock-inc/xkcd.job"
      tag: "0.3.15"
      digest: "sha256:2286c2e3643a96af9e3221c583c1c6c65659a8da3e7e7e814e589715911765c8"
      imagePullPolicy: Always
    env: []
    secretName: dotbot-secret
    schedule: "0 * * * 1,3,5"
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
    ttlSecondsAfterFinished: 2400
