nameOverride: ""
fullnameOverride: ""
gateway:
  replicaCount: 1
  image:
    repository: "ghcr.io/sillock-inc/bot.gateway"
    tag: "0.3.10"
    digest: "sha256:e133c95c887445bf8d52d164965eca29a43181d3b0c2aebeed102fecf36c7edb"
    pullPolicy: IfNotPresent
  secretName: dotbot-secret
  podAnnotations: { }
  podLabels: { }
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 2000
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumes: [ ]
  volumeMounts: [ ]

service:
  name: http
  type: LoadBalancer
  port: 80
  targetPort: 80
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - dotbot.local
  tls: []

jobs:
  - name: xkcd-job
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: "ghcr.io/sillock-inc/xkcd.job"
      tag: "0.3.10"
      digest: "sha256:ec0c29791d3ccbe2c0df1af667a7cc01b18516e5baf7b30da6f16f29a33d3bb5"
      imagePullPolicy: Always
    env: []
    secretName: dotbot-secret
    schedule: "0 * * * *"
    serviceAccount:
      name: "xkcd-job"
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
