nameOverride: ""
fullnameOverride: ""
deployments:
  - name: bot.gateway
    replicaCount: 1
    image:
      repository: "ghcr.io/sillock-inc/bot.gateway"
      tag: "0.1.4"
      digest: "sha256:b1a2a734d2e01ebd84f8527e5c85f31fd89731e309a7b838617f83fe1342d86e"
      pullPolicy: IfNotPresent
      podAnnotations: {}
      podLabels: {}
      podSecurityContext: {}
      # fsGroup: 2000 

      securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

      resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

      volumes: []
      # - name: foo
      #   secret:
      #     secretName: mysecret
      #     optional: false

      volumeMounts: []
      # - name: foo
      #   mountPath: "/etc/foo"
      #   readOnly: true
    service:
      name: http
      type: LoadBalancer
      port: 80
      targetPort: 80
      protocol: TCP
jobs:
  - name: xkcd.job
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: "ghcr.io/sillock-inc/xkcd.job"
      tag: "0.1.2"
      digest: "sha256:fbba5d889baa4ed46134134ab28227a3077b21c0edb09639e2003fcc5a23c509"
      imagePullPolicy: Always
    env:
      - name: ECHO_VAR
        value: "busybox"
    envFrom:
      - secretRef:
          name: dotbot-mongo
      - configMapRef:
          name: config_data
    schedule: "0 * * * *"
    serviceAccount:
      name: "xkcd-job"
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
ingress:
  enabled: false
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
