nameOverride: ""
fullnameOverride: ""
gateway:
  replicaCount: 1
  image:
    repository: "ghcr.io/opentoucan"
    tag: "1.0.0"
    pullPolicy: IfNotPresent
    main:
      name: "bot.gateway"
      digest: "sha256:a6357f77cb90dd27ee20f34beaa77e5c36aa47dd3fb5152d6a940ea9cf7b57df"
    migration:
      name: "bot.gateway.migration"
      digest: "ha256:93aba37d3228da4cd54176ea9f94e391bf4012eaf4999f501497582344a18bc6"
  secretName: dotbot-secret
  podAnnotations: { }
  podLabels: { }
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 2000
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumes: [ ]
  volumeMounts: [ ]

service:
  name: http
  type: LoadBalancer
  port: 80
  targetPort: 8080
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - dotbot.local
  tls: []

jobs:
  - name: xkcd-job
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: "ghcr.io/opentoucan"
      tag: "1.0.0"
      imagePullPolicy: Always
      main:
        name: "xkcd.job"
        digest: "sha256:1260888b92e648b0da5c8809035561842cb6935498c612fa4eba44fc966c0700"
      migration:
        name: "xkcd.job.migration"
        digest: "sha256:6e209a6038f705be20beb71cd939271624181c282ab7f33a8659b0e251807b16"
    secretName: dotbot-secret
    schedule: "0 * * * 1,3,5"
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
    ttlSecondsAfterFinished: 2400