nameOverride: ""
fullnameOverride: ""
gateway:
  replicaCount: 1
  image:
    repository: "ghcr.io/opentoucan"
    tag: "1.0.1"
    imagePullPolicy: IfNotPresent
    name: "dotbot.gateway"
    digest: "sha256:fffb516e18b492ca988c2f44b61b0b50e2d812a28364b84270a8858d92318467"
  secretName: dotbot-secret
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsUser: 1024
    runAsGroup: 1024
    fsGroup: 1024
    supplementalGroups: [1024]
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1024
    allowPrivilegeEscalation: false
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumes: []
  volumeMounts: []

migrator:
  image:
    repository: "ghcr.io/opentoucan"
    tag: "1.0.1"
    imagePullPolicy: IfNotPresent
    name: "dotbot.migration"
    digest: "sha256:88e60d1939c571bd179e91c27f37539d38713f22d352e4764f798f33bdf0f70a"
  secretName: dotbot-migrator-secret
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsUser: 1024
    runAsGroup: 1024
    fsGroup: 1024
    supplementalGroups: [1024]
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1024
    allowPrivilegeEscalation: false
  volumes:
    - name: cache-volume
      emptyDir:
        sizeLimit: 500Mi
  volumeMounts:
    - mountPath: /cache
      name: cache-volume
  env:
    - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
      value: /cache

service:
  name: http
  type: LoadBalancer
  port: 80
  targetPort: 8080
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - dotbot.local
  tls: []

jobs:
  - name: xkcd-job
    securityContext:
      runAsUser: 1024
      runAsGroup: 1024
      fsGroup: 1024
    image:
      repository: "ghcr.io/opentoucan"
      tag: "1.0.1"
      imagePullPolicy: Always
      main:
        name: "xkcd.job"
        digest: "sha256:bc47bcdd6c10a0903eb630cf529ce58ff1a3cb5596b2bc0279e7bbb48dd121ac"
    secretName: dotbot-secret
    schedule: "0 * * * 1,3,5"
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
    ttlSecondsAfterFinished: 2400
