nameOverride: ""
fullnameOverride: ""
gateway:
  replicaCount: 1
  image:
    repository: "ghcr.io/opentoucan/bot.gateway"
    tag: "0.3.23"
    digest: "sha256:d45e36a31268635feebcd72d385e17ce3558b377cc0c08110497358617b15387"
    pullPolicy: IfNotPresent
  secretName: dotbot-secret
  podAnnotations: { }
  podLabels: { }
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 2000
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumes: [ ]
  volumeMounts: [ ]

service:
  name: http
  type: LoadBalancer
  port: 80
  targetPort: 8080
  protocol: TCP

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - dotbot.local
  tls: []

jobs:
  - name: xkcd-job
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: "ghcr.io/opentoucan/xkcd.job"
      tag: "0.3.23"
      digest: "sha256:265740b239f7beac28b446be0c0b91551d3ea80810f3c5017ae4fdfc13cda91e"
      imagePullPolicy: Always
    secretName: dotbot-secret
    schedule: "0 * * * 1,3,5"
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
    ttlSecondsAfterFinished: 2400
