x-podman:
  in_pod: false

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ../dashboards:/var/lib/grafana/dashboards
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
