apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dotbot.fullname" . }}
  labels:
    {{- include "dotbot.labels" $ | nindent 4 }}
  {{- if .Values.configMapAnnotations }}
  annotations:
    {{- with .Values.configMapAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  {{- include "dotbot.configData" . | nindent 2 }}