{{- with .Values.gateway }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{- include "dotbot.fullname" $ }}"
  labels:
    {{- include "dotbot.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "dotbot.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dotbot.labels" $ | nindent 8 }}
        {{- with .podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: "{{- include "dotbot.name" $ }}"
      {{- end }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      initContainers:
        - image: {{ .image.repository }}/{{ .image.migration.name }}:{{ .image.tag | default $.Chart.AppVersion }}{{ if .image.migration.digest }}@{{ .image.migration.digest }}{{ end }}
          imagePullPolicy: {{ .image.imagePullPolicy }}
          name: "{{- include "dotbot.name" $ }}-migration"
          envFrom:
            - secretRef:
                name: {{ .secretName }}
      containers:
        - name: "{{- include "dotbot.name" $ }}"
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ .image.repository }}/{{ .image.main.name }}:{{ .image.tag | default $.Chart.AppVersion }}{{ if .image.main.digest }}@{{ .image.main.digest }} {{ end }}
          imagePullPolicy: {{ .image.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .secretName }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}