{{- if and (not .Values.existingAppSecret) (not (lookup "v1" "Secret" "" (printf "%s-%s" (include "dotbot.fullname" $) "secret")) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{- include "dotbot.fullname" $ }}-secret"
  labels:
    {{- include "dotbot.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- include "dotbot.secretsData" . | nindent 2 }}
{{- end }}