{{- if and (not .Values.existingMigratorSecret) (not (lookup "v1" "Secret" "" (printf "%s-%s-%s" (include "dotbot.fullname" $) "migrator" "secret"))) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{- include "dotbot.fullname" $ }}-migrator-secret"
  labels:
    {{- include "dotbot.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- include "dotbot.secretsMigratorData" . | nindent 2 }}
{{- end }}