{{- if not (lookup "v1" "Secret" "" (printf "%s-%s" (include "dotbot.fullname" $) "secret")) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{- include "dotbot.fullname" $ }}-secret"
type: Opaque
data:

{{- end }}
---
{{- if not (lookup "v1" "Secret" "" (printf "%s-%s-%s" (include "dotbot.fullname" $) "migrator" "secret")) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{- include "dotbot.fullname" $ }}-migrator-secret"
type: Opaque
data:
  CONNECTIONSTRING: {{ "Host=postgresql;Database=test;Username=test;Password=test;" | b64enc }}
{{- end }} 