{{- if not (lookup "v1" "Secret" "" (printf "%s-%s" (include "dotbot.fullname" $) "secret")) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{- include "dotbot.fullname" $ }}-secret"
type: Opaque
data:

{{- end }}