{{- with .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{- include "dotbot.name" $ }}"
  labels:
    {{- include "dotbot.labels" $ | nindent 4 }}
spec:
  type: {{ .type | default "ClusterIP" }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      nodePort: {{ .nodePort }}
  selector:
    {{- include "dotbot.selectorLabels" $ | nindent 4 }}
{{- end }}
