{
 "title": "Dotbot testing",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(dotbot_guilds_total,guild_id)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Guild Name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(guild_id, guild_name) (dotbot_guilds_total{guild_id=\"$server\"})",
     "legendFormat": "auto"
    }
   ]
  },
  {
   "title": "Custom Commands Queried",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(dotbot_fetched_custom_commands_total{guild_id=\"$server\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custom Commands Saved",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(dotbot_saved_custom_commands_total{guild_id=\"$server\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interaction Failures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(dotbot_exceptions_total{guild_id=\"$server\", otel_scope_name=\"dotbot\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Types",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "increase(dotbot_exceptions_total{guild_id=\"$server\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custom Command Saves by User",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(member_id, member_display_name) (dotbot_saved_custom_commands_total{guild_id=\"$server\"})",
     "legendFormat": "{{member_display_name}}"
    }
   ]
  },
  {
   "title": "Fetched Custom Commands",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(custom_command_name) (dotbot_fetched_custom_commands_total{guild_id=\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custom Command Queries by User",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(member_id, member_display_name) (dotbot_fetched_custom_commands_total{guild_id=\"$server\"})",
     "legendFormat": "{{member_display_name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{app=\"dotbot\"} |= `` | logfmt | label_format level=detected_level"
    }
   ]
  }
 ]
}