{
 "title": "Vehicle Dashboard for registration plate",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "registration_plate",
    "label": "Registration Plate",
    "query": "SELECT registration FROM vehicle_information"
   }
  ]
 },
 "panels": [
  {
   "title": "Vehicle Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Make",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT make FROM vehicle_information WHERE registration = '$registration_plate'"
      }
     ]
    },
    {
     "title": "Model",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT model from vehicle_information WHERE registration = '$registration_plate'"
      }
     ]
    },
    {
     "title": "Colour",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT colour from vehicle_information WHERE registration = '$registration_plate'"
      }
     ]
    },
    {
     "title": "Fuel Type",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT fuel_type from vehicle_information WHERE registration = '$registration_plate'"
      }
     ]
    },
    {
     "title": "Engine Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT CONCAT(engine_capacity_litres, 'L') as engine_capacity_litres from vehicle_information WHERE registration = '$registration_plate'"
      }
     ]
    },
    {
     "title": "Registration Date",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT registration_date as registration_date from vehicle_information WHERE registration = '$registration_plate'"
      }
     ]
    }
   ]
  },
  {
   "title": "Vehicle Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mileage over time",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 11, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT vi.\"registration\", vmt.\"completed_date\" as time, vmt.\"odometer_reading_in_miles\" as mileage, vi.\"make\", vi.\"model\"\nFROM vehicle_mot_test AS vmt\nINNER JOIN vehicle_information vi on vmt.\"vehicle_information_id\" = vi.\"id\"\nWHERE vi.registration = '$registration_plate' and $__timeFilter(vmt.\"completed_date\")\nORDER BY vmt.\"completed_date\" asc"
      }
     ]
    },
    {
     "title": "Valid MOT",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 11, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT mot_status_is_valid from vehicle_information WHERE registration = '$registration_plate'"
      }
     ]
    },
    {
     "title": "Taxed Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 15, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT tax_status_dvla_tax_status_text from vehicle_information WHERE registration = '$registration_plate'"
      }
     ]
    },
    {
     "title": "MOT Due Date",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 11, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "days" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT EXTRACT(DAY FROM mot_status_valid_until - now()) as days_remaining \nFROM vehicle_information \nWHERE registration = '$registration_plate';"
      }
     ]
    },
    {
     "title": "Tax Due Date",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 15, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "days" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT EXTRACT(DAY FROM tax_status_tax_due_date - now()) as days_remaining \nFROM vehicle_information \nWHERE registration = '$registration_plate';"
      }
     ]
    }
   ]
  },
  {
   "title": "MOT Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last recorded MOT result",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT result FROM vehicle_mot_test vmt\nINNER JOIN vehicle_information vi on vi.id = vmt.vehicle_information_id\nWHERE vi.registration = '$registration_plate'\nORDER BY vmt.completed_date DESC\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "MOT History Timeline",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 11 },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT \nvmt.result,\nvmt.test_number,\nvmt.completed_date,\nEXTRACT(EPOCH FROM DATE_TRUNC('year', vmt.completed_date)) as time\nFROM vehicle_mot_test vmt\nINNER JOIN vehicle_information vi on vi.id = vmt.vehicle_information_id\nWHERE vi.registration = '$registration_plate'"
      }
     ]
    },
    {
     "title": "MOT Tests",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT vmt.completed_date AS \"Test Date\", vmt.result AS \"MOT Result\", vmt.odometer_reading_in_miles AS \"Odometer (miles)\", STRING_AGG('[' || vmtd.category || ']\n' || vmidd.top_level_category || '\n' || vmidd.defect_name ,'\n\n' order by vmtd.category desc) AS \"Defect Details\" FROM vehicle_mot_test vmt\nINNER JOIN vehicle_information vi on vi.id = vmt.vehicle_information_id\nLEFT JOIN vehicle_mot_test_defect vmtd on vmtd.vehicle_mot_test_id = vmt.id\nLEFT JOIN mot_inspection_defect_definitions vmidd on vmidd.id = vmtd.defect_definition_id\nWHERE vi.registration = '$registration_plate'\nGROUP BY vmt.completed_date, vmt.result, vmt.odometer_reading_in_miles\nORDER BY vmt.completed_date DESC"
      }
     ]
    },
    {
     "title": "Defects per MOT Test",
     "type": "barchart",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "dataset": "dotbot",
       "rawSql": "SELECT vmt.completed_date as time,\n       COUNT(CASE WHEN vmtd.category = 'advisory' THEN vmtd.category END) as \"Advisory\",\n       COUNT(CASE WHEN vmtd.category = 'minor' THEN vmtd.category END) as \"Minor\",\n       COUNT(CASE WHEN vmtd.category = 'major' THEN vmtd.category END) as \"Major\",\n       COUNT(CASE WHEN vmtd.category not in('advisory', 'minor', 'major') THEN vmtd.category END) as \"Other\"\nFROM vehicle_mot_test_defect vmtd\n         RIGHT JOIN vehicle_mot_test vmt on vmt.id = vmtd.vehicle_mot_test_id\n         INNER JOIN vehicle_information vi on vi.id = vmt.vehicle_information_id\nWHERE vi.registration = '$registration_plate' and $__timeFilter(vmt.\"completed_date\")\nGROUP BY vmt.completed_date\nORDER BY vmt.completed_date DESC"
      }
     ]
    }
   ]
  },
  { "title": "Defect Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Last failed MOT defects",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "dotbot",
     "rawSql": "SELECT COUNT(*), vmidd.top_level_category FROM vehicle_mot_test_defect vmtd \nINNER JOIN (SELECT vmt.Id FROM vehicle_mot_test vmt\n                             INNER JOIN vehicle_information vi on vi.id = vmt.vehicle_information_id\n      WHERE vi.registration = '$registration_plate' AND vmt.result = 'failed'\n      ORDER BY vmt.completed_date DESC\n      LIMIT 1) vmt ON vmt.id = vmtd.vehicle_mot_test_id\n    INNER JOIN mot_inspection_defect_definitions vmidd on vmidd.id = vmtd.defect_definition_id\n--WHERE vmtd.category > 'advisory' maybe use distinct defect code so that all 4 corners of suspension arms don't skew results\nGROUP BY vmidd.top_level_category"
    }
   ]
  },
  {
   "title": "Most common MOT failure defect",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 16, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "dotbot",
     "rawSql": "SELECT COUNT(vmidd.\"id\"), CONCAT('(', regexp_replace(vmidd.\"top_level_category\", '\\d+\\.\\s+', ''), ') ', COALESCE(vmidd.\"sub_category_name\", vmidd.\"category_area\"))  \nFROM vehicle_mot_test_defect vmtd \nINNER JOIN vehicle_mot_test vmt ON vmtd.\"vehicle_mot_test_id\" = vmt.\"id\"\nINNER JOIN mot_inspection_defect_definitions vmidd ON vmtd.\"defect_definition_id\" = vmidd.\"id\"\nINNER JOIN vehicle_information vi ON vmt.vehicle_information_id = vi.id\nWHERE vi.registration = '$registration_plate' AND vmtd.\"category\" in ('dangerous', 'fail', 'major', 'minor')\nGROUP BY vmidd.\"sub_category_name\", vmidd.\"category_area\", vmidd.\"top_level_category\", vmt.\"result\"\nHAVING vmt.\"result\" = 'failed'  AND vmidd.\"category_area\" IS NOT NULL\nORDER BY COUNT(vmidd.\"id\") DESC"
    }
   ]
  },
  {
   "title": "MOT Failures over time",
   "type": "heatmap",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "dotbot",
     "rawSql": "SELECT $__timeGroupAlias(vmt.completed_date, '$__interval'),\n       CONCAT('(', regexp_replace(vmidd.\"top_level_category\", '\\d+\\.\\s+', ''), ') ', COALESCE(vmidd.\"sub_category_name\", vmidd.\"category_area\")) as category,\n       COUNT(*) as bucket\nFROM vehicle_mot_test_defect vmtd\n         INNER JOIN vehicle_mot_test vmt ON vmtd.\"vehicle_mot_test_id\" = vmt.\"id\"\n         INNER JOIN mot_inspection_defect_definitions vmidd ON vmtd.\"defect_definition_id\" = vmidd.\"id\"\n         INNER JOIN vehicle_information vi ON vmt.vehicle_information_id = vi.id\nWHERE vi.registration = '$registration_plate' \n  AND vmtd.\"category\" not in ('advisory') \n  AND vmt.\"result\" = 'failed' \nGROUP BY vmt.completed_date, vmidd.top_level_category, vmidd.sub_category_name, vmidd.category_area"
    }
   ]
  }
 ]
}