name: Release PR Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release-bot-gateway:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      packages: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
          config-file: src/Bot.Gateway/release-please-config.json
          manifest-file: src/Bot.Gateway/release-please-manifest.json

  release-xkcd-job:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      packages: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
          config-file: src/Xkcd.Job/release-please-config.json
          manifest-file: src/Xkcd.Job/release-please-manifest.json