name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["dotbot.gateway", "dotbot.migration"]
    permissions:
      contents: write
      packages: write
    environment:
      name: 'Production'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - uses: actions/setup-go@v5.2.0

      - name: Prep
        id: prep
        run: |
          echo "SEMVER=$(echo '${{ github.ref_name }}' | grep -o -P '(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?')" >> $GITHUB_OUTPUT

      - uses: imjasonh/setup-crane@v0.4
      - run: |
          crane tag "ghcr.io/${{ github.repository_owner }}/${{matrix.image}}:sha-${{ github.sha }}" "${{ steps.prep.outputs.SEMVER }}"
