---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Report

on:
  workflow_run:
    workflows: ['ci']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read

    steps:
      - name: Publish Test Report
        uses: dorny/test-reporter@df6247429542221bc30d46a036ee47af1102c451 # v2.7.0
        with:
          artifact: dotnet-results
          name: report
          path: '**/*.trx'
          reporter: dotnet-trx
